language: go

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - make lint
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script: make push

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
