apiVersion: v1
kind: Service
metadata:
  labels:
    app: world-bank-grpc
  name: world-bank-grpc
  namespace: world-bank-grpc
spec:
  ports:
  - port: 50001
    targetPort: 50001
  selector:
    app: world-bank-grpc
